export const PokemonTypeMap: Record<string, string> = {
  normal: "⚪️",
  fire: "🔥",
  water: "💧",
  electric: "⚡️",
  grass: "🌿",
  ice: "❄️",
  fighting: "🥊",
  poison: "☠️",
  ground: "🌍",
  flying: "🪽",
  psychic: "☯️",
  bug: "🐛",
  rock: "🪨",
  ghost: "👻",
  dragon: "🐉",
  dark: "🌚",
  steel: "⚙️",
  fairy: "🩷",
};
